---
- name: Installer NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Déployer la page HTML personnalisée
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: S'assurer que NGINX est démarré et activé
  service:
    name: nginx
    state: started
    enabled: yes